#!/bin/bash

print_color() {
  color="$1"
  shift
  echo -e "\033[${color}m$* \033[0m"
}

# Lint-Staged (Formatting + Typescript + Linting)
print_color 33 "\nRunning lint-staged (formatting + typescript + linting)..."
pnpm lint-staged
result=$? 

if [ "$result" -eq 0 ]; then
  print_color 32 "Lint-staged checks passed! ✅"
else
  print_color 31 "Lint-staged checks failed! ❌"
  print_color 31 "Please fix the issues before committing."
  exit 1
fi
