version: "3.8"

services:
  db:
    container_name: autopark_db
    image: postgres
    restart: always
    ports:
      - 2000:5432
    environment:
      - PORTGRES_USER: postgres
      - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD: password
    volumes:
      - db_data_autopark:/var/lib/postgresql/data
volumes:
  db_data_autopark: